In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

#Norma wektora, długość wektora w R^2


#### suma z kwadratów współrzędnych wektora

In [3]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [4]:
np.linalg.norm(v1)

4.123105625617661

# Norma euklidesowa w R^n

In [5]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

# Odległość 2 pkt na płaszczyźnie

In [6]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p - q)

5.0

In [7]:
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p - q)

5.0990195135927845

# Mnożenie macierzy


warunki: 
Liczba kolumn w lewej musi być liczbą wierszy w prawej.

Mnożenie macierzy nie jest przemienne 

In [8]:
x = np.array([[5,3], [3,9]])
y = np.array([[1],[-1]])
print(x)
print(y)


[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [9]:
print(x@y) # mnożenie macierzy przez znaczek @ lub:
print()
print(np.matmul(x,y)) # lub
print()
print(np.dot(x,y))

# w przypadku mnożenia y@x byłby błąd, nie spełnia warunków mnożenia macierzy

[[ 2]
 [-6]]

[[ 2]
 [-6]]

[[ 2]
 [-6]]


In [10]:
x = np.array([[2,-1,3],
              [3,1,0]])
y = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])

print(np.dot(x,y))

# macierz wynikowa zawsze ma tyle wierszy ile ma kolumn pierwsza macierz i tyle kolumn ile ma druga macierz

[[13  9 -4]
 [ 6  2 -1]]


# Wyznacznik macierzy


Przypominając: przekątna pierwsza wymnożona odjąć druga przekątna, dla rozmiaru 2x2.

Dla 3x3 - przekątne + przesunięcia (dopisywanie pomocnicze z boku bądź z dołu) - drugie przekątne wszystkie.

In [11]:
A = np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10

# Ślad macierzy


występuje dla kwadratowej,
suma elementów na przekątnej. I tyle

In [12]:
A = np.array([[2,4],[-1,3]])
np.trace(A)

5

# Macierz jednostkowa

typowa postać macierzy kwadratowej, wartości na przekątnej = 1.

In [13]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Macierz odwrotna

Tylko dla kwadratowej,
AB = BA = I
AB - macierze,
I - jednostkowa

In [15]:
A = np.array([[2,4],[-1,3]])
A

array([[ 2,  4],
       [-1,  3]])

In [16]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [17]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

# Macierz transponowana

zmiana wierszy na kolumny i odwrotnie

In [19]:
A = np.array([[2,1,-1],
              [0,-1,2]])
print(A)
print()
print(A.T)
print()
print(np.transpose(A))

[[ 2  1 -1]
 [ 0 -1  2]]

[[ 2  0]
 [ 1 -1]
 [-1  2]]

[[ 2  0]
 [ 1 -1]
 [-1  2]]


# Układy równań

AX = B

Jeżeli macierz układu A jest kwadratowa, to oznaczoność jest równa odwracalności, tzn.

AX = B
A^-1 AX = A^-1 B
X = A^-1 B

Przykład :         

In [20]:
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

# KONIEC ALGEBRY
# Funkcje statystyczne

In [21]:
price=np.array([[12.4, 12.8, 11.9, 12.6, 1000],
                [12.5, 13.0, 11.7, 12.6, 2000],
                [12.2, 13.4, 12.2, 13.2, 1500]])

print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.6 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [22]:
price.sum()

4650.5

In [23]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38.4, 4500. ])

In [24]:
price.sum(axis=1)

array([1049.7, 2049.8, 1551. ])

In [25]:
price.min()

11.7

In [26]:
price.mean(axis=0)

array([  12.3667,   13.0667,   11.9333,   12.8   , 1500.    ])

In [27]:
np.median(price)

12.6

In [28]:
np.mean(price)

310.03333333333336

In [29]:
np.std(price)

622.3653982098369

In [30]:
np.std(price, axis=0)

array([  0.1247,   0.2494,   0.2055,   0.2828, 408.2483])

In [31]:
np.var(price, axis=0)

array([     0.0156,      0.0622,      0.0422,      0.08  , 166666.6667])