In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.19.5


In [ ]:
help(np.array)

## 1D Array

In [8]:
x = np.array([1,3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
len(x)

2

In [14]:
x.shape

(2,)

In [15]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [18]:
x = np.array([1.4,2.3,1.7])
print(x)

[1.4 2.3 1.7]


In [19]:
x.dtype

dtype('float64')

##2D Array

In [20]:
x = np.array([[1,2],[-3,1]])

In [21]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [23]:
x.size

4

In [24]:
x = np.array([[1,2,4],[4,2,1]])

In [25]:
print(x.size)
print(x.ndim)
print(x.shape)

6
2
(2, 3)


## 3D Array

In [32]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
      [5,6,2]],
     
     [[5,6,7],
      [3,4,5]]]
)

In [33]:
print(x.size)
print(x.ndim)
print(x.shape)

18
3
(3, 2, 3)


#Typy danych

In [34]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [35]:
A = np.array([1.0,2.2,3.7])
A.dtype

dtype('float64')

In [36]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [37]:
A

array([1., 2., 3.])

In [38]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [39]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [41]:
A = np.array([1.0,2.2,3.7], dtype='int')
A.dtype

dtype('int64')

In [42]:
A

array([1, 2, 3])

In [43]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [44]:
A = np.array([24,120,230],dtype=np.int8)
A.dtype

dtype('int8')

In [45]:
A

array([ 24, 120, -26], dtype=int8)

In [46]:
A = np.array([24,120,230],dtype=np.uint8)
A.dtype

dtype('uint8')

In [47]:
A

array([ 24, 120, 230], dtype=uint8)

# Tworzenie Tablic

In [48]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
np. ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.ones(shape=(5,5), dtype='int')


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.full(shape=(3,3), fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(start=5, stop=15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.arange(start=5, stop=15, step=2)

array([ 5,  7,  9, 11, 13])

In [58]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [60]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [63]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Operacje na tablicach

In [70]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [73]:
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A%B)

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]
[0 0 1 0]


In [74]:
print(A+3)
print(A*2)
print(A/2)
print(A+3*B)

[6 4 7 5]
[6 2 8 4]
[1.5 0.5 2.  1. ]
[12 -2 13  8]


In [75]:
np.add(A,B)

array([6, 0, 7, 4])

In [76]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [77]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [78]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [79]:
# Mnożenie macierzowe

x = np.array([[1,3],[-2,0]])
y = np.array([[6,0],[-1,2]])

In [81]:
print(np.matmul(x,y))
print()
print(np.dot(x,y))

[[  3   6]
 [-12   0]]

[[  3   6]
 [-12   0]]


In [82]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [83]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [84]:
x @ y

array([[  3,   6],
       [-12,   0]])

In [85]:
y@x

array([[ 6, 18],
       [-5, -3]])

# Generowanie liczb pseudolosowych

In [91]:
np.random.seed(0)


In [92]:
np.random.randn()

1.764052345967664

In [93]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [94]:
np.random.randn(10,4)


array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [95]:
np.random.rand()

0.1965823616800535

In [96]:
np.random.rand(10)


array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [97]:
np.random.rand(19,4)


array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782],
       [0.39650574, 0.8811032 , 0.58127287, 0.88173536],
       [0.69253159, 0.72525428, 0.50132438, 0.95608363],
       [0.6439902 , 0.42385505, 0.60639321, 0.0191932 ],
       [0.30157482, 0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233, 0.56996491],
       [0.59087276, 0.57432525, 0.65320082, 0.65210327],
       [0.43141844, 0.8965466 , 0.36756187, 0.43586493],
       [0.89192336, 0.80619399,

In [98]:
np.random.randint(10) #zwraca nieujemne do wartości górnej podanej jako argument

8

In [99]:
np.random.randint(low=10,high=101)

12

In [100]:
np.random.randint(low=10,high=101, size=10)


array([37, 93, 99, 33, 63, 61, 56, 30, 63, 39])

In [101]:
np.random.choice([4,2,1,4])

4

In [104]:
np.random.choice([4,2,1,4], size=2)


array([2, 4])

In [105]:
np.random.choice(['python','java','sql'])

'sql'

In [106]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.random.shuffle(data)

In [108]:
data

array([0, 5, 4, 6, 8, 9, 1, 7, 3, 2])

#Podstawowe funkcje

In [109]:
np.exp(1)

2.718281828459045

In [112]:
np.sqrt(9)

3.0

In [113]:
np.all([2,3,1])

True

In [114]:
np.all([2,3,0])

False

In [115]:
np.any([2,3,0])

True

In [116]:
np.any([0,0,0])

False

In [118]:
A = np.random.rand(5)
A

array([0.17949026, 0.1709866 , 0.46345098, 0.87457296, 0.94411975])

In [119]:
np.argmax(A)

4

In [120]:
A[np.argmax(A)]

0.9441197509175635

In [121]:
A[np.argmin(A)]

0.17098659868313149

In [122]:
np.argsort(A)

array([1, 0, 2, 3, 4])

In [126]:
np.max(A)

0.9441197509175635

In [127]:
np.min(A)

0.17098659868313149

In [128]:
np.mean(A)

0.526524109109606

In [129]:
np.median(A)

0.46345097738448293

In [130]:
np.std(A)

0.33055763614851075

# Indeksowanie, wycinanie

In [131]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
#A[idx]
print(A[3])
print(A[2:])
print(A[:2])
print(A[[0,4]])
print(A[-1])

3
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1]
[0 4]
19


In [135]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
A[:,0]

array([ 0,  5, 10, 15])

In [137]:
A[:,-1]

array([ 4,  9, 14, 19])

In [139]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [141]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [142]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [143]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [144]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [145]:
for item in A.flat: #wypłaszcza
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [146]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#Zmiana rozmiaru tablic

In [147]:
A.shape

(4, 5)

In [148]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [149]:
A.ravel() #wypłaszcza też

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [150]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [155]:
A.T #transponowanie macierzy

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [157]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [158]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [162]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [163]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [164]:
np.bitwise_or(A <-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])