## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [4]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A,B))

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [5]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A,B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [6]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate((data,target),axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [7]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [28]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
print(A)

A1,A2,A3 = np.split(A, [2,6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0 0 2 5 0 1 1]
 [0 0 6 4 1 4 1 1]
 [0 0 5 5 5 1 1 1]
 [0 0 6 5 2 5 1 1]
 [0 0 2 3 0 0 1 1]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0 2 5 0]
 [6 4 1 4]
 [5 5 5 1]
 [6 5 2 5]
 [2 3 0 0]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [17]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

36

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [29]:
np.count_nonzero(A, axis=1)

array([4, 6, 6, 6, 4])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [19]:
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
A

array([[ 0.4245,  0.9405, -0.8676,  0.1459],
       [-1.3699, -0.7718,  0.8787, -0.2396],
       [ 1.2094,  0.538 ,  2.7344,  0.0938],
       [-1.4064, -0.0345, -0.963 ,  0.9772],
       [ 0.042 , -0.1373, -0.1241,  0.7403],
       [-0.4525,  0.777 ,  1.0456, -0.3421],
       [-0.926 , -0.513 ,  0.7101,  0.0925],
       [ 0.6301,  1.7629,  0.231 , -0.8089],
       [ 1.0574,  0.0514,  0.8724,  1.0662],
       [-0.959 ,  1.382 ,  0.9051, -0.6039]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [22]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [25]:
A = np.random.randn(8, 4)
print(A)
A = np.delete(A,2, axis=1)
A

[[ 0.40497551  0.90973817 -0.20245753  0.06089661]
 [ 0.6471627   0.12609483 -1.89737698  1.28054076]
 [-0.61513368  2.11131764  0.68684851  0.07097242]
 [ 0.43932714 -0.10849789 -0.48643277  0.20759826]
 [ 0.88499047 -0.46452975 -0.62223716 -0.35548864]
 [ 0.95201109  1.45255025  0.36201391  0.58131413]
 [-0.62970086  0.87675465  0.55173701 -0.71012796]
 [-1.78767161 -1.2205701  -0.66920273  1.16193732]]


array([[ 0.40497551,  0.90973817,  0.06089661],
       [ 0.6471627 ,  0.12609483,  1.28054076],
       [-0.61513368,  2.11131764,  0.07097242],
       [ 0.43932714, -0.10849789,  0.20759826],
       [ 0.88499047, -0.46452975, -0.35548864],
       [ 0.95201109,  1.45255025,  0.58131413],
       [-0.62970086,  0.87675465, -0.71012796],
       [-1.78767161, -1.2205701 ,  1.16193732]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [26]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [27]:
A = np.random.randint(10, size=(100, 30))
np.set_printoptions(edgeitems=10)
A

array([[4, 0, 6, 6, 8, 2, 8, 0, 0, 3, ..., 2, 9, 4, 4, 2, 8, 3, 4, 3, 4],
       [6, 8, 6, 4, 9, 9, 6, 9, 4, 2, ..., 8, 1, 9, 1, 4, 4, 5, 2, 7, 0],
       [5, 3, 0, 6, 8, 3, 3, 5, 2, 5, ..., 8, 6, 0, 2, 8, 0, 8, 7, 0, 5],
       [4, 5, 9, 4, 5, 4, 4, 3, 2, 2, ..., 6, 8, 9, 7, 5, 7, 4, 7, 9, 3],
       [9, 7, 9, 1, 4, 8, 3, 5, 0, 8, ..., 9, 7, 1, 4, 6, 7, 0, 5, 0, 1],
       [0, 4, 9, 8, 5, 0, 0, 1, 8, 2, ..., 6, 4, 4, 4, 9, 9, 2, 0, 4, 8],
       [0, 2, 3, 0, 0, 7, 1, 7, 6, 9, ..., 0, 6, 4, 4, 1, 2, 6, 5, 1, 5],
       [1, 1, 1, 2, 1, 3, 8, 5, 0, 7, ..., 0, 3, 7, 4, 1, 5, 4, 1, 2, 8],
       [6, 6, 5, 7, 3, 7, 3, 7, 8, 2, ..., 4, 5, 0, 4, 8, 9, 1, 0, 9, 8],
       [9, 8, 8, 5, 7, 0, 9, 3, 0, 7, ..., 7, 2, 6, 2, 6, 1, 9, 5, 2, 2],
       ...,
       [1, 7, 9, 0, 7, 6, 6, 2, 0, 3, ..., 2, 1, 7, 6, 8, 1, 3, 5, 2, 7],
       [2, 1, 2, 5, 1, 7, 0, 6, 1, 9, ..., 7, 6, 5, 6, 4, 6, 0, 0, 8, 4],
       [4, 2, 4, 2, 8, 8, 5, 0, 6, 6, ..., 4, 7, 5, 3, 6, 7, 1, 6, 1, 1],
       [7, 1, 8, 0, 8, 0, 