In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

#Metryki - klasyfikacja binarna


Accuary - dokładność klasyfikacji

In [2]:
y_true = np.array([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
                   1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
                   1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [3]:
from sklearn.metrics import accuracy_score

accuracy_score(y_true, y_pred)

0.8

In [4]:
results = pd.DataFrame({'y_true':y_true, 'y_pred':y_pred})
results

y_true  y_pred
0        1       0
1        0       0
2        1       1
3        1       1
4        0       0
5        1       1
6        1       0
7        0       0
8        1       1
9        0       1
10       1       0
11       1       1
12       0       0
13       1       1
14       1       1
15       0       0
16       1       0
17       1       1
18       0       0
19       1       1
20       1       1
21       1       1
22       0       1
23       1       1
24       1       1
25       0       0
26       1       1
27       1       1
28       0       0
29       1       1

In [8]:
results = results.sort_values(by='y_true')
result = results.reset_index()
results['sample'] = result.index + 1
results

y_true  y_pred  sample
18       0       0       1
9        0       1       2
12       0       0       3
7        0       0       4
4        0       0       5
25       0       0       6
28       0       0       7
15       0       0       8
1        0       0       9
22       0       1      10
11       1       1      11
13       1       1      12
2        1       1      13
3        1       1      14
5        1       1      15
14       1       1      16
8        1       1      17
10       1       0      18
6        1       0      19
24       1       1      20
21       1       1      21
27       1       1      22
17       1       1      23
16       1       0      24
19       1       1      25
0        1       0      26
20       1       1      27
23       1       1      28
26       1       1      29
29       1       1      30

In [9]:
fig = make_subplots(rows=2, cols=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_true'], mode='markers', name='y_true'), row=1, col=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_pred'], mode='markers', name='y_pred'), row=2, col=1)
fig.update_layout(width=900, height=500, title='Klasyfikator binarny')
fig.show()

Klasyfikacja binarna - macierz konfuzji/pomyłek

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

In [13]:
import plotly.figure_factory as ff

def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1','true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), colorscale='ice',
                                      showscale=True, reversescale=True)
    fig.update_layout(width=500, height=500, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)
    

## Metryki na podstawie macierzy konfuzji

In [14]:
cm

array([[ 8,  2],
       [ 4, 16]])

In [15]:
cm.ravel()

array([ 8,  2,  4, 16])

In [16]:
tn, fp, fn, tp = cm.ravel()

In [17]:
print(tn)
print(fp)
print(fn)
print(tp)

8
2
4
16


In [18]:
# Type I error - False Positive Rate

fpr = fp / (fp + tn)
fpr

0.2

In [20]:
# Type II error - False Negative Rate
fnr = fn / (fn + tp)
fnr

0.2

In [21]:
# Presicion - ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne
precision = tp/ (tp + fp)
precision

0.8888888888888888

In [22]:
# Recall - ile obserwacji z wszystkich sklasyfikowane jako pozytywne
recall = tp / (tp + fn)
recall

0.8

# Krzywa ROC

In [23]:
from sklearn.metrics import roc_curve

fpr, tpr, thresh = roc_curve(y_true, y_pred, pos_label=1) #pos label przekazuje klasę pozytywną

roc = pd.DataFrame({'fpr':fpr, 'tpr':tpr})
roc

fpr  tpr
0  0.0  0.0
1  0.2  0.8
2  1.0  1.0

In [24]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1)

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='red', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='navy')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800,
                                    height=400))
    fig.show()
plot_roc_curve(y_true, y_pred)

# Metryki - klasyfikacja wieloklasowa

In [25]:
y_true = np.array([1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2])
y_pred = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 2, 2])

accuracy_score(y_true, y_pred)

0.7241379310344828

Maciesz konfuzji/pomyłek

In [28]:
cm = confusion_matrix(y_true, y_pred)
cm

array([[ 6,  1,  0],
       [ 3, 10,  2],
       [ 0,  2,  5]])

In [29]:
def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1', 'pred_2'], index=['true_2','true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), 
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)


###Raport klasyfikacji

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.86      0.75         7
           1       0.77      0.67      0.71        15
           2       0.71      0.71      0.71         7

    accuracy                           0.72        29
   macro avg       0.72      0.75      0.73        29
weighted avg       0.73      0.72      0.72        29



In [31]:
print(classification_report(y_true, y_pred, target_names=['label_1', 'label_2', 'label_3']))


              precision    recall  f1-score   support

     label_1       0.67      0.86      0.75         7
     label_2       0.77      0.67      0.71        15
     label_3       0.71      0.71      0.71         7

    accuracy                           0.72        29
   macro avg       0.72      0.75      0.73        29
weighted avg       0.73      0.72      0.72        29

