In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import plotly.express as px

## Wprowadzenie - pierwszy model.

Model sekwencyjny to nic innego jak liniowy stos warstw

In [2]:
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną, należy użyć warstwy Dense. Aby dodać warstwę do modelu należy użyć metody .add()

In [3]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

## wyświetlenie podsumowania modelu

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


## Funkcje aktywacji
 Istotnym elementem sieci nieuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje te jak nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

 Jeżeli jej nie określimy, domyślnie będzie to funkcja liniowa tzn f(x)=x

 Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosowane są różne funkcja, aby rozwiązywać problemy nieliniowe.


In [6]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data':random_data, 'linear':linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [7]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3,3])

In [8]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data':random_data,'sigmoid':sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [9]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.2,1.2])

In [10]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data':random_data,'relu':relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [11]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-3,3])

In [12]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data':random_data,'tanh':tanh(random_data)})
data.head()
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-3,3])

In [13]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


## Kompilacja modelu

Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:

* rodzaj optymalizatora
* funkcję straty
* metryki, które będziemy obserwować podczas trenowania sieci

In [14]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

## Trenowanie modelu

Za dane wejściowe do modelu należy przekazać Numpy arrays:

* epochs - krtoność iteracji przez sieć w trakcie uczenia
* batch_size - rozmiar wsadu po którym następuje aktualizacja wag
* validation_split - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* validation_data - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [15]:
# model.fit(data, labels, epochs=10, batch_size=32) #batch_size=32 domyślnie
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2) #zbiór walidacyjny to dobra praktyka.
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

## Przykład - klasyfikacja binarna

In [16]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [17]:
data[:3]

array([[-0.7278029 , -0.63631212, -1.05110819,  0.37068299,  0.59506021,
        -0.2352721 , -0.6569656 , -1.22586193, -0.17803708,  1.5111277 ,
        -0.86185097,  0.20032354, -1.28636877,  0.93771018,  0.06624013,
         0.09294047, -0.01909049,  0.0615547 , -0.36323735,  0.83577225,
        -1.17105058,  0.75846674, -0.43215645,  0.89412252,  0.16729987,
        -1.77978686, -1.71622379,  0.02838177, -0.92017841,  0.04856221,
        -0.84918066,  0.01036712, -0.11075697,  0.74946698, -1.59309823,
        -0.14723311, -0.34878836, -0.73515118, -0.69022145,  2.49388149,
        -0.11232656, -0.51537269,  1.25337108, -0.12082982, -0.24931192,
         0.58795013,  2.50013193, -1.62786624, -0.36318179, -0.35144344,
        -0.47961748,  1.03443508,  0.58985116,  0.50720329, -0.54719335,
         1.07784417,  0.23928813,  0.48342649, -0.61346867,  0.86048172,
        -1.61967537,  0.15049028,  0.74276656, -1.2873555 , -0.42117142,
        -2.24758143, -1.56873587,  0.37638518, -0.6

In [18]:
labels[:10]

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0]])

In [19]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 1s 1ms/step - loss: 0.7324 - accuracy: 0.4968
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6911 - accuracy: 0.5465
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6763 - accuracy: 0.5812
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6640 - accuracy: 0.5969
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6519 - accuracy: 0.6236
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6399 - accuracy: 0.6423
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6256 - accuracy: 0.6553
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6121 - accuracy: 0.6693
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5986 - accuracy: 0.6826
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5845 - accuracy: 0.6947

In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 1s 1ms/step - loss: 0.7734 - accuracy: 0.4966
Epoch 2/20
157/157 [==============================] - 0s 2ms/step - loss: 0.7050 - accuracy: 0.5365
Epoch 3/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6846 - accuracy: 0.5645
Epoch 4/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6707 - accuracy: 0.5875
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6586 - accuracy: 0.6087
Epoch 6/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6475 - accuracy: 0.6220
Epoch 7/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6369 - accuracy: 0.6472
Epoch 8/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6267 - accuracy: 0.6560
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6168 - accuracy: 0.6683
Epoch 10/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6065 - accuracy: 0.6784

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.7495 - accuracy: 0.5021 - val_loss: 0.7274 - val_accuracy: 0.4925
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6962 - accuracy: 0.5425 - val_loss: 0.7208 - val_accuracy: 0.4820
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6758 - accuracy: 0.5746 - val_loss: 0.7211 - val_accuracy: 0.4860
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6602 - accuracy: 0.6011 - val_loss: 0.7254 - val_accuracy: 0.4960
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6459 - accuracy: 0.6280 - val_loss: 0.7298 - val_accuracy: 0.4990
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6304 - accuracy: 0.6504 - val_loss: 0.7336 - val_accuracy: 0.4930
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6160 - accuracy: 0.6695 - val_loss: 0.7411 - val_accuracy: 0.4865
Epoch 

In [22]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [23]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [24]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.7602 - accuracy: 0.5030 - val_loss: 0.7174 - val_accuracy: 0.5175
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7002 - accuracy: 0.5416 - val_loss: 0.7113 - val_accuracy: 0.5195
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6780 - accuracy: 0.5755 - val_loss: 0.7148 - val_accuracy: 0.5130
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6615 - accuracy: 0.6050 - val_loss: 0.7185 - val_accuracy: 0.5015
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6473 - accuracy: 0.6249 - val_loss: 0.7188 - val_accuracy: 0.5185
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6315 - accuracy: 0.6524 - val_loss: 0.7226 - val_accuracy: 0.5035
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6167 - accuracy: 0.6715 - val_loss: 0.7320 - val_accuracy: 0.5055
Epoch 

In [25]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [26]:
x = model.predict(test_data)
x

array([[0.45242435],
       [0.3077416 ],
       [0.6153905 ],
       [0.33489764],
       [0.8172767 ]], dtype=float32)

In [27]:
#model.predict_proba(test_data) nie ma funkcji, jest równoważna model.predict

In [28]:
#model.predict_classes(test_data) też nie ma funkcji 

In [29]:
y_pred = np.argmax(x,axis=1)
y_pred

array([0, 0, 0, 0, 0])

## Przykład - klasyfikacja wieloklasowa

In [30]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [31]:
labels[:10]

array([[3],
       [4],
       [0],
       [2],
       [3],
       [7],
       [8],
       [2],
       [5],
       [1]])

In [32]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [33]:
labels[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [34]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))
model.compile(
    optimizer='rmsprop',
    loss = 'categorical_crossentropy',
    metrics=['accuracy'])

model.fit(data,labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3151 - accuracy: 0.0988 - val_loss: 2.3051 - val_accuracy: 0.1025
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1019 - val_loss: 2.3039 - val_accuracy: 0.0990
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3023 - accuracy: 0.1059 - val_loss: 2.3084 - val_accuracy: 0.0975
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3008 - accuracy: 0.1050 - val_loss: 2.3029 - val_accuracy: 0.1085
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2981 - accuracy: 0.1125 - val_loss: 2.3084 - val_accuracy: 0.0855
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2969 - accuracy: 0.1156 - val_loss: 2.3081 - val_accuracy: 0.0970
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2931 - accuracy: 0.1160 - val_loss: 2.3107 - val_accuracy: 0.0940
Epoch 

In [35]:
test_data = np.random.random((10,150))

predict = model.predict(test_data)
predict

array([[0.05909647, 0.09563313, 0.05932325, 0.21448413, 0.08880873,
        0.07422995, 0.06867043, 0.12334916, 0.10737541, 0.10902932],
       [0.12151103, 0.10154542, 0.09040073, 0.07170586, 0.05856259,
        0.11974416, 0.12345625, 0.09268603, 0.10352121, 0.11686673],
       [0.13567592, 0.09655669, 0.0844932 , 0.10404052, 0.10626557,
        0.04249116, 0.10749305, 0.08582729, 0.10822803, 0.1289286 ],
       [0.21898474, 0.09532169, 0.08675886, 0.05781822, 0.07022776,
        0.0794154 , 0.09111978, 0.08074389, 0.10855909, 0.11105064],
       [0.05906748, 0.0874984 , 0.23065813, 0.05104256, 0.05104207,
        0.13822462, 0.10001671, 0.16640984, 0.04320386, 0.07283635],
       [0.04561529, 0.06801146, 0.07983931, 0.07333389, 0.25684297,
        0.03402036, 0.131506  , 0.06913836, 0.08817387, 0.1535184 ],
       [0.09124137, 0.08642453, 0.14047049, 0.07679421, 0.09383959,
        0.12620783, 0.13247174, 0.11113041, 0.06414208, 0.07727764],
       [0.1098069 , 0.08022657, 0.0915006

In [36]:
np.argmax(predict,axis=1)

array([3, 6, 0, 0, 2, 4, 2, 4, 3, 2])

# Przykład - regresja

In [37]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [38]:
labels[:10]

array([44.06490314, 47.6107465 , 17.92418098, 19.84921678, 27.06560848,
       39.23284534, 26.67302832, 28.81011958, 48.38992255, 45.04070564])

In [39]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data,labels,epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 299.5494 - val_loss: 212.5919
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 211.5153 - val_loss: 213.0746
Epoch 3/30
250/250 [==============================] - 0s 2ms/step - loss: 211.0623 - val_loss: 213.1673
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 210.9526 - val_loss: 212.7498
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 210.7228 - val_loss: 213.4328
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 210.3423 - val_loss: 215.3320
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 210.0831 - val_loss: 212.8904
Epoch 8/30
250/250 [==============================] - 0s 2ms/step - loss: 209.9858 - val_loss: 215.8560
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 209.7223 - val_loss: 213.2383
Epoch 10/30
250/250 [==============================] - 0s 2ms/st

In [41]:
model = Sequential()

model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data,labels,epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 13.6967 - mse: 266.7415 - val_loss: 12.6985 - val_mse: 212.6050
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5848 - mse: 211.8467 - val_loss: 12.6970 - val_mse: 212.6428
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5749 - mse: 211.7754 - val_loss: 12.7005 - val_mse: 212.7742
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5600 - mse: 211.4167 - val_loss: 12.7053 - val_mse: 212.9607
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5487 - mse: 210.9858 - val_loss: 12.6942 - val_mse: 212.8074
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5329 - mse: 211.0750 - val_loss: 12.6973 - val_mse: 212.9399
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5392 - mse: 210.7542 - val_loss: 12.7045 - val_mse: 213.1809
Epoch 8/10
250/250 [==============

In [42]:
test_data = np.random.random((10,150))

model.predict(test_data)

array([[26.126322],
       [26.160614],
       [28.488382],
       [23.768702],
       [24.69646 ],
       [29.742323],
       [25.92615 ],
       [27.769476],
       [26.665066],
       [26.574858]], dtype=float32)